name: reusable workflow
on: 
  workflow_dispatch:

jobs:
  call-workflow-1-in-local-repo:
    uses: AmauryVanEspen/sfeir-github-action-training/.github/workflows/ex4-reusable-workflow.yaml@main
    with:
        NODE_VERSION: 'lts'